### ISSUE TITLE
Crear componente de bootcamp

### ISSUE THREAD

**Issue by OscarGonzalez97** [OscarGonzalez97/bootcamp-landing#1]
El componente de bootcamp es una tarjeta con titulo imagen de la tecnologia, una breve descripcion y un boton para ir al detalle de ese bootcamp. Similar al de los cursos de Platzi. Utilizar tailwind para que sea responsive. 

<img width="1188" alt="image" src="https://github.com/OscarGonzalez97/bootcamp-landing/assets/36247829/72297692-fdbb-46e5-a8e4-f351a6057782">

**Comment by agustinramirez1** [comment]
Finalizado
