### ISSUE TITLE
Detalle de bootcamp (estatico)

### ISSUE THREAD

**Issue by OscarGonzalez97** [OscarGonzalez97/bootcamp-landing#15]
Detalle de la pagina de un bootcamp, crear solo uno por ahora para tener como referencia(luego se cargara dinamicamente). En la pagina debe estar todo lo relacionado a el segun su modelo (pizarron):
* Titulo
* Descripcion
* Imagen
* Modulos y contenidos (pueden ser el componente accordion)

**Comment by malweis** [comment]
Detalle estatico terminado
