### ISSUE TITLE
Crear componente accordion

### ISSUE THREAD

**Issue by OscarGonzalez97** [OscarGonzalez97/bootcamp-landing#17]
Cear componente accordion que va tener generalmente un texto y en la descripción varios temas.
Ejemplo: 
Collapsed:
![image](https://github.com/OscarGonzalez97/bootcamp-landing/assets/36247829/b6536e5f-77bf-4eda-968a-f5c906fca625)
Extendido:
![image](https://github.com/OscarGonzalez97/bootcamp-landing/assets/36247829/52e8ea19-461d-45f4-a5d4-3ee93e61fa3c)

**Comment by malweis** [comment]
este commit lo añade 0ac4433
