### ISSUE TITLE
Crear schema de blog

### ISSUE THREAD

**Issue by OscarGonzalez97** [OscarGonzalez97/bootcamp-landing#22]
El schema debe contener:
* Titulo
* Escrito por
* Avatar (imagen) de escrito por
* Un campo que sea "**contenido**" y sea de este tipo: https://www.sanity.io/docs/block-type o puede ser este otro ejemplo: https://www.sanity.io/docs/what-you-need-to-know-about-block-text

**Comment by tobiasvera17** [comment]
Agrego:
- Fecha de publicación del contenido
